dist: xenial
language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DATABASE = postgres://postgres@localhost/travis_ci_test
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE ROLE app WITH LOGIN CREATEDB;'
  - psql -c 'CREATE DATABASE dbcarpool OWNER app;'
  - ls /etc/postgresql/9.6/main
  - sudo cat /etc/postgresql/9.6/main/pg_hba.conf
  - sudo cp pg_hba_travis.conf /etc/postgresql/9.6/main/pg_hba.conf
  - sudo systemctl restart postgresql
  - psql dbcarpool -U app -f sql/test_schema.sql
script:
  - python app_test.py
