dist: xenial
language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DATABASE = postgres://postgres@localhost/travis_ci_test
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE ROLE app WITH LOGIN CREATEDB;'
  - psql -c 'CREATE DATABASE dbcarpool_test OWNER app;'
  - sudo cp pg_hba_travis.conf /etc/postgresql/9.6/main/pg_hba.conf
  - sudo systemctl restart postgresql
  - psql dbcarpool_test -U app -f tests/test_script.sql
script:
  #- python -m unittest discover
  - python tests/test_app.py
